### ISSUE TITLE
Future of the project?

### ISSUE THREAD

**Issue by cascardian** [alexrp/oninaki-reincarnation#1]
This mod basically makes the game into its definitive edition (another fine example of gamers fixing companies' mistakes), but I saw that you removed this from your pinned repositories, but haven't archived it or anything. Since you committed some changes after the first release that never made it into one, I wondered whether you were just waiting for the UABE bug to be fixed before any further work or whether you've lost interest. That'd be fine, of course.

**Comment by alexrp** [comment]
I might do another release of the mod since the changes I made to invincibility frames not only address some balance issues, but actually fix some bugs in the game where e.g. activating dash skill "upgrades" would result in *less* invincibility frames.

Beyond that, I probably won't work on this particular project anymore. I'm still working on modding the game, but I'm taking a radically different approach. I've decided to rip out the base game's code (i.e. everything in `Assembly-CSharp.dll`) and rewrite it from scratch as a multiplayer experience, reusing all the art assets from the base game.

Needless to say, this is a huge undertaking that will take a long time, and, to be fair, might never come to fruition. But it's become clear to me that working within the confines of the base game's 'engine' is really painful, not just for me, but for the original developers as well. The game's battle direction system is a serious mess that is incredibly hard to reason about, let alone modify. The developers made tons of mistakes in writing the 'scripts' for many skills in the game. This became especially apparent to me when I was working on 1f56bc458b3b681b5318d05c14d92a7dd14c8fdf; half of the changes in that commit are me just fixing mistakes in the original data.

Anyway, I have no objection if someone wants to take over this project. It just didn't seem to me that there's a whole lot of interest in this project based on the general lack of feedback since I released it, so I never made any sort of formal announcement about shelving it.
